// Every event the audit log can hold, with the plain words shown on screen.
// A new event is added here once; the model, the filter and the screen all read this list.
export const AUDIT_ACTIONS = Object.freeze({
  LOGIN_SUCCESS: 'Logged in',
  LOGIN_FAILED: 'Login failed',
  LOGIN_RATE_LIMITED: 'Too many login attempts',
  LOGOUT: 'Logged out',
  PASSWORD_CHANGED: 'Password changed',
  PASSWORD_RESET: 'Password reset',
  USER_CREATED: 'Account created',
  USER_UPDATED: 'Account updated',
  USER_ACTIVATED: 'Account activated',
  USER_DEACTIVATED: 'Account deactivated',
  HOSPITAL_CREATED: 'Hospital created',
  HOSPITAL_UPDATED: 'Hospital updated',
  HOSPITAL_ACTIVATED: 'Hospital activated',
  HOSPITAL_DEACTIVATED: 'Hospital deactivated',
  MEMBER_ADDED: 'Staff added to hospital',
  MEMBER_ROLES_CHANGED: 'Staff roles changed',
  MEMBER_ACTIVATED: 'Staff access activated',
  MEMBER_DEACTIVATED: 'Staff access deactivated',
  MASTER_CREATED: 'Master data added',
  MASTER_UPDATED: 'Master data updated',
  MASTER_ACTIVATED: 'Master data activated',
  MASTER_DEACTIVATED: 'Master data deactivated',
  HOSPITAL_SWITCHED: 'Switched hospital',
  SETTINGS_UPDATED: 'Hospital settings changed',
  OPD_TIMINGS_UPDATED: 'OPD timings changed',
  PROFILE_UPDATED: 'Professional details changed',
  // Patients (ids and field names only – never medical details)
  PATIENT_REGISTERED: 'Patient registered',
  PATIENT_REGISTERED_ANYWAY: 'Patient registered despite a possible duplicate',
  PATIENT_VIEWED: 'Patient record opened',
  PATIENT_UPDATED: 'Patient record changed',
  PATIENT_CLOSED: 'Patient record closed',
  PATIENT_REOPENED: 'Patient record reopened',
  PATIENT_EMERGENCY_ACCESS: 'Emergency access to a patient record',
  // Billing
  PRICE_ITEM_CREATED: 'Price list item added',
  PRICE_ITEM_UPDATED: 'Price list item changed',
  BILL_CREATED: 'Bill created',
  BILL_UPDATED: 'Bill changed',
  BILL_DISCOUNTED: 'Discount given',
  BILL_CANCELLED: 'Bill cancelled',
  PAYMENT_RECEIVED: 'Payment received',
  REFUND_GIVEN: 'Refund given',
  BILLING_SETTINGS_UPDATED: 'Billing settings changed',
  BILLS_EXPORTED: 'Bills exported',
  // Pharmacy
  MEDICINE_CREATED: 'Medicine added',
  MEDICINE_UPDATED: 'Medicine changed',
  SUPPLIER_CREATED: 'Supplier added',
  SUPPLIER_UPDATED: 'Supplier changed',
  PURCHASE_RECORDED: 'Purchase recorded',
  SALE_MADE: 'Medicines sold',
  SALE_RETURNED: 'Medicines returned',
  STOCK_ADJUSTED: 'Stock written off or corrected',
  ORDER_CREATED: 'Purchase order made',
  ORDER_UPDATED: 'Purchase order changed',
  ORDER_SENT: 'Purchase order sent',
  ORDER_CANCELLED: 'Purchase order cancelled',
  ORDER_CLOSED: 'Purchase order closed',
  SUPPLIER_RETURN_MADE: 'Stock returned to a supplier',
  SUPPLIER_RETURN_CANCELLED: 'Return to a supplier cancelled',
  // Appointments (ids only)
  APPOINTMENT_BOOKED: 'Appointment booked',
  APPOINTMENT_MOVED: 'Appointment moved',
  APPOINTMENT_CANCELLED: 'Appointment cancelled',
  APPOINTMENT_ARRIVED: 'Patient arrived',
  APPOINTMENT_SEEN: 'Patient seen',
  APPOINTMENT_ARRIVAL_UNDONE: 'Arrival undone',
  APPOINTMENT_LINKED: 'Quick booking linked to a patient',
  APPOINTMENT_REMINDER_SENT: 'Appointment reminder sent',
  // Lab (ids and test keys only – never results)
  LAB_ORDERED: 'Lab tests ordered',
  LAB_COLLECTED: 'Lab sample collected',
  LAB_REPORTED: 'Lab results reported',
  LAB_AMENDED: 'Lab results amended',
  LAB_REVIEWED: 'Lab results reviewed',
  LAB_CANCELLED: 'Lab order cancelled',
  LAB_VIEWED: 'Lab order opened',
  // Visits (ids and the part saved only – never medical details)
  VISIT_STARTED: 'Visit started',
  VISIT_VIEWED: 'Visit opened',
  VISIT_UPDATED: 'Visit changed',
  PRESCRIPTION_SAVED: 'Prescription written',
  VISIT_SIGNED: 'Visit signed',
  VISIT_CANCELLED: 'Visit marked as entered in error',
  VISIT_ADDITION: 'Correction added to a signed visit',
  // Inpatients (ids only)
  ADMITTED: 'Patient admitted',
  ADMISSION_VIEWED: 'Stay opened',
  ADMISSION_UPDATED: 'Ward or bed changed',
  INPATIENTS_VIEWED: 'Inpatient list opened',
  INPATIENT_DOC_STARTED: 'Ward document started',
  INPATIENT_DOC_SAVED: 'Ward document saved',
  INPATIENT_DOC_SIGNED: 'Ward document signed',
  INPATIENT_DOC_CANCELLED: 'Ward document marked as entered in error',
  INPATIENT_DOC_ADDITION: 'Correction added to a ward document',
  NURSING_ENTRY: 'Nursing chart entry',
  NURSING_ENTRY_CANCELLED: 'Nursing chart entry marked as entered in error',
  DISCHARGED: 'Patient discharged',
  DISCHARGES_VIEWED: 'Discharge list opened',
  DISCHARGE_CARD_VIEWED: 'Discharge card opened',
  // Medical history and scanned documents (ids and the kind of document only)
  HISTORY_VIEWED: 'Medical history opened',
  DOCUMENT_UPLOADED: 'Patient document uploaded',
  DOCUMENT_VIEWED: 'Patient document opened',
  DOCUMENT_CANCELLED: 'Patient document marked as entered in error',
  // Clinic library
  LIBRARY_CREATED: 'Clinic library entry added',
  LIBRARY_UPDATED: 'Clinic library entry changed',
  LIBRARY_APPROVED: 'Clinic library entry approved',
  LIBRARY_ACTIVATED: 'Clinic library entry activated',
  LIBRARY_DEACTIVATED: 'Clinic library entry deactivated',
});

export const AUDIT_ACTION_KEYS = Object.keys(AUDIT_ACTIONS);

// Simple groups for filtering the audit log, by the start of the event name. An event not matched falls in "other".
const GROUPS = [
  { key: 'logins', label: 'Logins and passwords', prefixes: ['LOGIN', 'LOGOUT', 'PASSWORD', 'HOSPITAL_SWITCHED'] },
  { key: 'accounts', label: 'Accounts and staff', prefixes: ['USER', 'MEMBER', 'PROFILE'] },
  { key: 'hospitals', label: 'Hospitals and settings', prefixes: ['HOSPITAL_', 'SETTINGS', 'OPD', 'MASTER'] },
  { key: 'patients', label: 'Patient records', prefixes: ['PATIENT', 'VISIT', 'PRESCRIPTION', 'ADMIT', 'ADMISSION', 'INPATIENT', 'NURSING', 'DISCHARGE', 'HISTORY', 'DOCUMENT'] },
  { key: 'billing', label: 'Billing', prefixes: ['BILL', 'PAYMENT', 'REFUND', 'PRICE'] },
  { key: 'pharmacy', label: 'Pharmacy', prefixes: ['MEDICINE', 'SUPPLIER', 'PURCHASE', 'SALE', 'STOCK', 'ORDER_'] },
  { key: 'appointments', label: 'Appointments', prefixes: ['APPOINTMENT'] },
  { key: 'lab', label: 'Lab', prefixes: ['LAB_'] },
  { key: 'library', label: 'Clinic library', prefixes: ['LIBRARY'] },
];
const groupOf = (action) => GROUPS.find((g) => g.prefixes.some((p) => action.startsWith(p)))?.key ?? 'other';

export const AUDIT_CATEGORIES = [...GROUPS, { key: 'other', label: 'Other' }].map(({ key, label }) => ({
  key,
  label,
  actions: AUDIT_ACTION_KEYS.filter((a) => groupOf(a) === key),
})).filter((c) => c.actions.length);

// Routine entries: a record opened, a sign-in or sign-out, a hospital switch. Kept like every entry, but the log hides
// them unless asked ("include record openings and sign-ins"), so the changes stand out.
export const ROUTINE_ACTIONS = AUDIT_ACTION_KEYS.filter((a) => a.endsWith('_VIEWED') || ['LOGIN_SUCCESS', 'LOGOUT', 'HOSPITAL_SWITCHED'].includes(a));
